all:
	gcc -Wall -g hidingNoNullImg.c -o hidingNoNullImg
	gcc -Wall -g restoringNullBytes.c -o restoringNullBytes
	gcc -Wall -g retrievingNoNullImg.c -o retrievingNoNullImg
	gcc -Wall -g strippingNullBytes.c -o strippingNullBytes